# -*- coding: utf-8 -*-
"""FStep1_dataFiltering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B1NmmDN98FWbKHrUg5g82sA19GdKvVhl
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

# read the dataset
PATH = "/content/drive/Shareddrives/1:1_Krishna_Vijay/Dataset/original/all_stocks_5yr.csv"

# read the csv
data = pd.read_csv(PATH)
data.head()

# select the company as APPLE
COMPANY = "MSFT"

data_MSFT = data[data["Name"] == COMPANY]
data_MSFT.drop("Name", axis = 1, inplace = True)
data_MSFT.head()
data_MSFT.to_csv("/content/drive/Shareddrives/1:1_Krishna_Vijay/Dataset/original/MSFT_dataset.csv",index=False)

data_MSFT

COMPANY = "MSFT"

data_MSFT = data[data["Name"] == COMPANY]
data_MSFT.drop("Name", axis = 1, inplace = True)
data_MSFT.head()
data_MSFT.to_csv("/content/drive/Shareddrives/1:1_Krishna_Vijay/Dataset/original/MSFT_data.csv",index=False)

data_MSFT

COMPANY = "AMD"

data_AMD = data[data["Name"] == COMPANY]
data_AMD.drop("Name", axis = 1, inplace = True)
data_AMD.head()
data_AMD.to_csv("/content/drive/Shareddrives/1:1_Krishna_Vijay/Dataset/original/AMD_data.csv",index=False)

data_AMD